// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// haversineDistance
NumericVector haversineDistance(NumericVector fromLat, NumericVector fromLon, NumericVector toLat, NumericVector toLon);
RcppExport SEXP _transportr_haversineDistance(SEXP fromLatSEXP, SEXP fromLonSEXP, SEXP toLatSEXP, SEXP toLonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type fromLat(fromLatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type fromLon(fromLonSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type toLat(toLatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type toLon(toLonSEXP);
    rcpp_result_gen = Rcpp::wrap(haversineDistance(fromLat, fromLon, toLat, toLon));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_transportr_haversineDistance", (DL_FUNC) &_transportr_haversineDistance, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_transportr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
