# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

haversineDistance <- function(fromLat, fromLon, toLat, toLon) {
    .Call(`_transportr_haversineDistance`, fromLat, fromLon, toLat, toLon)
}

